# Change these first
owner: chdtv # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Bot
    url: 
  - name: Server 1
    url: https://stream1.servers.chd-tv.tk/
  - name: Server 2
    url: http://stream3.servers.chd-tv.tk/admin
  - name: Server 3
    url: https://stream6.servers.chd-tv.tk/

status-website:
  cname: status.chd-tv.tk
  favicon: https://raw.githubusercontent.com/chdtv/uptime/master/logo.png
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/chdtv/uptime/master/logo.png
  name: CHD-TV
  introTitle: "**CHD-TV** status"
  introMessage: This is a status page which uses **real-time** data from our servers
  navbar:
    - title: Status
      href: /
i18n:
  footer: '[https://t.me/chdiptv](https://t.me/chdiptv)'
  incidentViewOnGitHub: ''
